services:
  - type: web
    name: valentine-gift-maker
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPI_ID
        sync: false
